stages:
  data_ingestion:
    cmd: python src/carcinomaDetection/pipeline/stage_01_data_ingestion.py
    deps:
      - src/carcinomaDetection/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Data
  
  prepare_base_model:
    cmd: python src/carcinomaDetection/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/carcinomaDetection/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/carcinomaDetection/pipeline/stage_03_model_trainer.py
    deps:
      - src/carcinomaDetection/pipeline/stage_03_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/Data/train
      - artifacts/data_ingestion/Data/valid
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - EPOCHS
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/carcinomaDetection/pipeline/stage_04_model_evaluation.py
    deps:
      - src/carcinomaDetection/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Data/test
      - artifacts/training/model.h5
    params:
      - BATCH_SIZE
      - IMAGE_SIZE
    metrics:
      - scores.json:
          cache: False
