artifacts_root: artifacts # path to the directory where artifacts will be stored

data_ingestion:
  root_dir: artifacts/data_ingestion # path to the directory where data will be ingested
  source_url: https://drive.google.com/file/d/1QtnMBvt2zue-BicSfNVNUxRpwAHdTVyu/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip # path to the local data file
  unzip_dir: artifacts/data_ingestion


prepare_base_model: 
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


training:
  root_dir: artifacts/training
  trained_model_file_path: artifacts/training/model.h5


  
  